# Generated by Django 6.0.4 on 2026-05-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ricambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=50, unique=True)),
                ('descrizione', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('quantita_disponibile', models.IntegerField(default=0)),
                ('soglia_minima', models.IntegerField(default=5)),
                ('prezzo_acquisto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prezzo_vendita', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Ricambi',
            },
        ),
        migrations.CreateModel(
            name='MovimentoMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrata', 'Entrata (Rifornimento)'), ('uscita', 'Uscita (Riparazione)')], max_length=10)),
                ('quantita', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ordine_lavoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='officina.ordinelavoro')),
                ('ricambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='magazzino.ricambio')),
            ],
            options={
                'verbose_name_plural': 'Movimenti Magazzino',
            },
        ),
    ]
