# Generated by Django 6.0.4 on 2026-05-04 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_apertura', models.DateTimeField(auto_now_add=True)),
                ('data_chiusura', models.DateTimeField(blank=True, null=True)),
                ('stato', models.CharField(choices=[('attesa', 'In Attesa'), ('lavorazione', 'In Lavorazione'), ('completato', 'Completato'), ('consegnato', 'Consegnato')], default='attesa', max_length=20)),
                ('note_interne', models.TextField(blank=True)),
                ('meccanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='clienti.veicolo')),
            ],
            options={
                'verbose_name': 'Ordine di Lavoro',
                'verbose_name_plural': 'Ordini di Lavoro',
            },
        ),
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('ore_lavorate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('costo_manodopera', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventi', to='officina.ordinelavoro')),
            ],
            options={
                'verbose_name': 'Singolo Intervento',
                'verbose_name_plural': 'Dettaglio Interventi',
            },
        ),
    ]
