# Generated by Django 6.0.4 on 2026-05-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('codice_fiscale', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Veicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('anno', models.PositiveIntegerField()),
                ('km', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veicoli', to='clienti.cliente')),
            ],
            options={
                'verbose_name': 'Veicolo',
                'verbose_name_plural': 'Veicoli',
            },
        ),
    ]
