# Generated by Django 6.0.4 on 2026-05-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('data_emissione', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('fattura', 'Fattura')], default='fattura', max_length=20)),
                ('totale_manodopera', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totale_ricambi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva_applicata', models.IntegerField(default=22)),
                ('totale_ivato', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento_fiscale', to='officina.ordinelavoro')),
            ],
            options={
                'verbose_name_plural': 'Fatture e Preventivi',
            },
        ),
    ]
