# Generated by Django 6.0.4 on 2026-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='stato',
            field=models.CharField(choices=[('bozza', 'In attesa'), ('approvato', 'Approvato'), ('rifiutato', 'Rifiutato')], default='bozza', max_length=20),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='numero_documento',
            field=models.CharField(help_text='Es: PREV-001 o FATT-001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('fattura', 'Fattura')], default='preventivo', max_length=20),
        ),
    ]
