# Generated by Django 6.0.4 on 2026-05-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatturazione', '0002_fattura_stato_alter_fattura_numero_documento_and_more'),
        ('officina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fattura',
            options={'verbose_name_plural': 'Fatture'},
        ),
        migrations.AddField(
            model_name='fattura',
            name='numero_progressivo',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fattura',
            name='stato_pagamento',
            field=models.CharField(choices=[('non_pagato', 'Non Pagato'), ('parziale', 'Parziale'), ('pagato', 'Pagato')], default='non_pagato', max_length=20),
        ),
        migrations.AlterField(
            model_name='fattura',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Es: PREV-001 o FATT-001', max_length=40, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('approvato', 'Approvato'), ('rifiutato', 'Rifiutato')], default='bozza', max_length=20)),
                ('totale_manodopera', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totale_ricambi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ordine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preventivo', to='officina.ordinelavoro')),
            ],
            options={
                'verbose_name': 'Preventivo',
                'verbose_name_plural': 'Preventivi',
            },
        ),
    ]
